CREATE DATABASE IF NOT EXISTS customer_behaviour_analysis_project;
USE customer_behaviour_analysis_project;

SELECT * FROM cust_data;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue 
FROM cust_data
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM cust_data
WHERE discount_applied= "Yes" AND purchase_amount>= (SELECT AVG(purchase_amount) FROM cust_data);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS Average_Product_Rating
FROM cust_data
GROUP BY item_purchased
ORDER BY Average_Product_Rating
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, Round(AVG(purchase_amount),2) AS "Average Purchase Amount"
FROM cust_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, COUNT(customer_id), 
ROUND(AVG(purchase_amount),2) AS "Average Purchaese Amount",
SUM(purchase_amount) AS "Total Revenue"
FROM cust_data
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
CONCAT(ROUND((SUM(CASE WHEN discount_applied= "Yes" THEN 1 ELSE 0 END) /COUNT(*)) *100,2), "%" ) AS discount_rate
FROM cust_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
 /* WITH clause creates a Common Table Expression (CTE). */
 /* A CTE acts like a temporary result set—almost like a virtual table—that is defined at the beginning 
 of a query and then referenced in main SELECT, INSERT, UPDATE, or DELETE statement. */
 WITH customer_type AS(
 SELECT customer_id, previous_purchases,
 CASE
	WHEN previous_purchases=1 THEN "New"
    WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
    ELSE "Loyal"
    END AS customer_segment
    FROM cust_data
 )
 
SELECT customer_segment, COUNT(*) AS 'Number of Customers'
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
SELECT category, item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM cust_data
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS "Number of Customers"
FROM cust_data
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER by COUNT(customer_id) DESC;

-- Q10. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount) AS "Total Revenue"
FROM cust_data
GROUP BY age_group
ORDER BY SUM(purchase_amount) DESC;